### PR TITLE
Add filesystem migration syscall

### PR DESCRIPTION
**Pull request by sosthene-nitrokey**
Motivated by https://github.com/Nitrokey/fido-authenticator/pull/55 and https://github.com/trussed-dev/trussed-auth/pull/39

### CODE REVIEW

**Review by robin-nitrokey — COMMENTED** [review]
I don’t fully understand this PR currently.  Do you have a branch that shows who this would look like in the runner?

My understanding is:
1. Applications and backends can define migration functions with the signature `fn(&dyn DynFilesystem, &dyn DynFilesystem)`.
2. The runner registers these migration functions when setting up the trussed-staging backend and assigns a versioning scheme.
3. The migrations are then triggered by the runner using a syscall that provides the versions.

My open questions:
- Why are the migrations implemented as a syscall if they are only triggered by the runner?  Couldn’t the runner just call some function of the backend?
- This provides applications with much more privileges than they actually need.  Can’t we use a `DynClientFilestore` for application migrations and something like a `BackendFilestore` for backend migrations?
- How is the current FS version stored?  Shouldn’t it be managed by the backend?

**Comment by robin-nitrokey** [comment]
> Migrations are triggered by the admin app.

But still during the boot/setup process and not triggered by a command?

**Comment by sosthene-nitrokey** [comment]
Yes

**Comment by robin-nitrokey** [comment]
> Maybe running it manually would be better, but the trussed service owns the filesystem when the admin app is loaded.

I think we can always directly access the filesystems in the runner because `Store` requires `Copy`.  Similar to what we do with the provisioner.

**Comment by sosthene-nitrokey** [comment]
Right. 

I'll migrate to that then. We can merge the split and merge migrations later.

**Comment by sosthene-nitrokey** [comment]
Moving the migration logic and type definitions to the admin-app creates a dependency loop.

I guess we will have split the se050-manage extension from the backend itself.

**Pull request closed without merging**
